remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Tracer
description: Signature-based Static Analysis for Detecting Recurring Vulnerabilities
